/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/guitar.glb 
Author: ironcladmax501 (https://sketchfab.com/IronCladMax501)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guitar-7ab6e59ba93b46bd8afa981fef92f114
Title: Guitar
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/guitar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube64_Neck_0.geometry} material={materials.Neck} />
      <mesh geometry={nodes.pCube64_Neck2_0.geometry} material={materials.Neck2} />
      <mesh geometry={nodes.pCube64_neckFace_0.geometry} material={materials.neckFace} />
      <mesh geometry={nodes.pCube64_SilverLace_0.geometry} material={materials.SilverLace} />
      <mesh geometry={nodes.pCube64_mattBlack_0.geometry} material={materials.mattBlack} />
      <mesh geometry={nodes.pCube64_sliver1_0.geometry} material={materials.sliver1} />
      <mesh geometry={nodes.pCube64_lambert2_0.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.pCube64_Bronze_0.geometry} material={materials.Bronze} />
      <mesh geometry={nodes.pCube64_DirtyBronze_0.geometry} material={materials.DirtyBronze} />
      <mesh geometry={nodes.pCube64_Chrome_0.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.pCube64_wood2_0.geometry} material={materials.wood2} />
      <mesh geometry={nodes.pCube64_Wood_2_0.geometry} material={materials.Wood_2} />
      <mesh geometry={nodes.pCube64_wood_0.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/guitar.glb')
